<?php
// +----------------------------------------------------------------------
// | Title   : 后台管理继承类
// +----------------------------------------------------------------------
// | Created : Henrick (me@hejinmin.cn)
// +----------------------------------------------------------------------
// | From    : Shenzhen wepartner network Ltd
// +----------------------------------------------------------------------
// | Date    : 2018/6/28 19:53
// +----------------------------------------------------------------------


namespace app\common\controller;


use think\Controller;

class AdminController extends Controller
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function _empty(){
        return $this->_response(404,'not found this page');
    }

    protected function _response($err,$msg='',$data=[]){
        return json([
            'err' => $err,
            'msg' => $msg,
            'data'=> $data
        ]);
    }
}